package exe.weazy.reko.util.values

const val PREFERENCES_FILENAME = "MEMES_PREFS"

const val APPLICATION_KEY = "APPLICATION_KEY"
const val APPLICATION_SECRET_KEY = "APPLICATION_SECRET_KEY"
const val RECOGNIZER_KEY = "RECOGNIZER_KEY"

const val SKY_BIOMETRY_RECOGNIZER = "SKY_BIOMETRY_RECOGNIZER"
const val LOCAL_RECOGNIZER = "LOCAL_RECOGNIZER"

const val IMAGE_PATH = "IMAGE_PATH"

const val REQUEST_CAMERA_CODE = 101
const val REQUEST_GALLERY_CODE = 102
const val REQUEST_READ_EXTERNAL_STORAGE_CODE = 103